name: Test Deploy

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout..
        uses: actions/checkout@v2

      - name: Heroku..
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nfs-storage"
          email: "jarbull002@gmail.com"
          usedocker: true
        env:
          TOKEN_CI: ${{secrets.TOKEN_CI}}
